# configs/config.yaml
defaults:
  - experiment: experiment_base
  - dataset: dataset_base
  - train: train_base
  - sampler: sampler_base
  - model: model_base
  - logging: logging_base
seed: 42
gpu_id: 2