# configs/config.yaml
defaults:
  - experiment: cpf_base
  - dataset: dataset_base
  - train: train_base
  - sampler: sampler_base
  - model: cpf_student
  - logging: logging_base
  - teacher: gcn
#  - teacher_train: train_base
  - _self_

seed: 5
gpu_id: 2
teacher_checkpoint: "/app"

#teacher:
#  model: gcn
#  checkpoint: "/app"   # 기본값(런에서 override로 덮어씀)

hydra:
  run:
    dir: outputs/${kst:%Y-%m-%d}/${kst:%H-%M-%S}
  sweep:
    dir: multirun/${kst:%Y-%m-%d}/${kst:%H-%M-%S}
    subdir: ${hydra.job.num}
