# configs/sweep/test.yaml

# 3-layer

# 3-hop fanout
sampler:
  sizes: [15, 10, 5]
  batch_size: 2048
  num_workers: 4
  shuffle: true

# sweep search space
model:
  num_layers: 3
  hidden_dim: [64]
  dropout: [0.0, 0.5]

train:
  lr: [0.005]
  weight_decay: [5e-5]
