name: kd_basic

# 공통 하이퍼파라미터
epochs: 200
lr: 0.01
weight_decay: 5e-4

# distillation 여부
use_distill: true
kd_type: basic

# phase 구조 추가 (optional)
phases:
  - name: pretrain
    epochs: 50
    lr: 0.003
    weight_decay: 0.0
    use_distill: false

  - name: distill
    epochs: 100
    lr: 0.003
    weight_decay: 0.0
    use_distill: true
    kd_type: basic

  - name: finetune
    epochs: 50
    lr: 0.001
    weight_decay: 0.0
    use_distill: false
